CREATE TABLE IF NOT EXISTS `MYMYSQLLOG` (
	`ID_MYMYSQLLOG` INT AUTO_INCREMENT,
    `DATEHOUR` DATETIME DEFAULT CURRENT_TIMESTAMP(),
    `LOG` VARCHAR(250),
    `ERROR` VARCHAR(250),
	CONSTRAINT PK_MYMYSQLLOG PRIMARY KEY (`ID_MYMYSQLLOG`)
)ENGINE=INNODB;
